# BK_pyth/reflex_app.py
from reflex import Reflex

class MyApp(Reflex):
    def render_menu(self):
            return """
                    <nav>
                                <ul>
                                                <li><a href="/">Home</a></li>
                                                                <li><a href="/section1">Section 1</a></li>
                                                                                <li><a href="/section2">Section 2</a></li>
                                                                                            </ul>
                                                                                                    </nav>
                                                                                                            """

                                                                                                                def render_home(self):
                                                                                                                        return f"""
                                                                                                                                <html>
                                                                                                                                        <head>
                                                                                                                                                    <title>Reflex App</title>
                                                                                                                                                            </head>
                                                                                                                                                                    <body>
                                                                                                                                                                                {self.render_menu()}
                                                                                                                                                                                            <div id="content">
                                                                                                                                                                                                            <h1>Home</h1>
                                                                                                                                                                                                                            <p>Welcome to the home page!</p>
                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                        </html>
                                                                                                                                                                                                                                                                """

                                                                                                                                                                                                                                                                    def render_section1(self):
                                                                                                                                                                                                                                                                            return f"""
                                                                                                                                                                                                                                                                                    <html>
                                                                                                                                                                                                                                                                                            <head>
                                                                                                                                                                                                                                                                                                        <title>Reflex App - Section 1</title>
                                                                                                                                                                                                                                                                                                                </head>
                                                                                                                                                                                                                                                                                                                        <body>
                                                                                                                                                                                                                                                                                                                                    {self.render_menu()}
                                                                                                                                                                                                                                                                                                                                                <div id="content">
                                                                                                                                                                                                                                                                                                                                                                <h1>Section 1</h1>
                                                                                                                                                                                                                                                                                                                                                                                <p>This is section 1.</p>
                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                    </body>
                                                                                                                                                                                                                                                                                                                                                                                                            </html>
                                                                                                                                                                                                                                                                                                                                                                                                                    """

                                                                                                                                                                                                                                                                                                                                                                                                                        def render_section2(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                return f"""
                                                                                                                                                                                                                                                                                                                                                                                                                                        <html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <title>Reflex App - Section 2</title>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {self.render_menu()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div id="content">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h1>Section 2</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>This is section 2.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app = MyApp()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.run()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            