pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";

contract DecentralizedExchange {
    
        using SafeERC20 for IERC20;
            
                address public admin;
                    
                        struct Token {
                                bytes32 ticker;
                                        address tokenAddress;
                                            }
                                                
                                                    mapping(bytes32 => Token) public tokens;
                                                        bytes32[] public tokenList;
                                                            mapping(address => mapping(bytes32 => uint)) public balances;
                                                                mapping(bytes32 => mapping(bytes32 => uint)) public orders;
                                                                    mapping(bytes32 => mapping(bytes32 => bool)) public orderExists;
                                                                        
                                                                            event Deposit(address indexed account, bytes32 indexed ticker, uint amount);
                                                                                event Withdraw(address indexed account, bytes32 indexed ticker, uint amount);
                                                                                    event Order(bytes32 indexed ticker, uint amount, bytes32 indexed orderType, uint price, address indexed trader);
                                                                                        
                                                                                            constructor() {
                                                                                                    admin = msg.sender;
                                                                                                        }
                                                                                                            
                                                                                                                function addToken(bytes32 ticker, address tokenAddress) external {
                                                                                                                        require(msg.sender == admin, "Only admin can add tokens");
                                                                                                                                tokens[ticker] = Token(ticker, tokenAddress);
                                                                                                                                        tokenList.push(ticker);
                                                                                                                                            }
                                                                                                                                                
                                                                                                                                                    function deposit(uint amount, bytes32 ticker) external {
                                                                                                                                                            IERC20(tokens[ticker].tokenAddress).safeTransferFrom(msg.sender, address(this), amount);
                                                                                                                                                                    balances[msg.sender][ticker] += amount;
                                                                                                                                                                            emit Deposit(msg.sender, ticker, amount);
                                                                                                                                                                                }
                                                                                                                                                                                    
                                                                                                                                                                                        function withdraw(uint amount, bytes32 ticker) external {
                                                                                                                                                                                                require(balances[msg.sender][ticker] >= amount, "Insufficient balance");
                                                                                                                                                                                                        balances[msg.sender][ticker] -= amount;
                                                                                                                                                                                                                IERC20(tokens[ticker].tokenAddress).safeTransfer(msg.sender, amount);
                                                                                                                                                                                                                        emit Withdraw(msg.sender, ticker, amount);
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                    function createOrder(bytes32 ticker, uint amount, bytes32 orderType, uint price) external {
                                                                                                                                                                                                                                            require(orderType == "buy" || orderType == "sell", "Invalid order type");
                                                                                                                                                                                                                                                    require(tokens[ticker].tokenAddress != address(0), "Token does not exist");
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                    if (orderType == "buy") {
                                                                                                                                                                                                                                                                                require(balances[msg.sender]["ETH"] >= amount * price, "Insufficient ETH balance");
                                                                                                                                                                                                                                                                                            IERC20(tokens[ticker].tokenAddress).safeTransferFrom(msg.sender, address(this), amount);
                                                                                                                                                                                                                                                                                                        balances[msg.sender][ticker] += amount;
                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                            require(balances[msg.sender][ticker] >= amount, "Insufficient token balance");
                                                                                                                                                                                                                                                                                                                                        balances[msg.sender]["ETH"] += amount * price;
                                                                                                                                                                                                                                                                                                                                                    balances[msg.sender][ticker] -= amount;
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                            if (orderExists[ticker][orderType]) {
                                                                                                                                                                                                                                                                                                                                                                                        orders[ticker][orderType] += amount;
                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                            orders[ticker][orderType] = amount;
                                                                                                                                                                                                                                                                                                                                                                                                                        orderExists[ticker][orderType] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                emit Order(ticker, amount, orderType, price, msg.sender);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                            function executeOrder(bytes32 ticker, uint amount, bytes32 orderType, uint price, address trader) external {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    require(msg.sender == admin, "Only admin can execute orders");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            require(orderExists[ticker][orderType], "Order does not exist");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    require(orders[ticker][orderType] >= amount, "Insufficient order amount");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   